import { PortfolioData } from './types';

export const initialPortfolioData: PortfolioData = {
  profile: {
    name: 'Hemant Singh Rana',
    title: 'Full-Stack Software Engineer',
    subTitle: 'Java 21, Spring Boot 3 & React.js Developer',
    email: 'iamhemant1289@gmail.com',
    phone: '+91-9082712612',
    location: 'Dehradun, Uttarakhand, India',
    profileImageUrl: '/uploads/profilePic.png',
    heroBio: 'Dynamic Full-Stack Software Engineer specializing in backend development using Java 21, Spring Boot 3, and React.js. Experienced in designing scalable RESTful APIs, implementing secure JWT-based authentication, developing database-driven applications using Spring Data JPA and Hibernate, and building responsive web interfaces.',
    status: 'Available for SDE Roles & Internships',
    typingWords: [
      'Full-Stack Software Engineer',
      'Java 21 & Spring Boot 3',
      'React.js & Tailwind CSS',
      'RESTful APIs & Clean Architecture',
      'Smart India Hackathon Winner',
    ],
    socialLinks: [
      {
        platform: 'GitHub',
        url: 'https://github.com/hemant1883',
        iconName: 'Github',
      },
      {
        platform: 'LinkedIn',
        url: 'https://linkedin.com/in/hemant-singh',
        iconName: 'Linkedin',
      },
    ],
  },
  about: {
    headline: 'Dynamic Full-Stack Software Engineer specializing in Java 21, Spring Boot 3, and React.js.',
    careerObjective: 'Passionate about applying Clean Architecture, DTO patterns, and object-oriented design principles to develop scalable, maintainable software solutions.',
    journey: 'Specializing in backend development using Java 21, Spring Boot 3, and React.js. Experienced in designing scalable RESTful APIs, implementing secure JWT-based authentication, developing database-driven applications using Spring Data JPA and Hibernate, and building responsive web interfaces.',
    education: [
      {
        degree: 'Bachelor of Technology (B.Tech.) in Computer Science and Engineering',
        institution: 'Swami Rama Himalayan University, Dehradun',
        duration: 'Aug 2023 – Ongoing',
        grade: 'CGPA: 7.5 | NAAC A+ Grade',
        highlights: [
          'Java 21 Virtual Threads & Spring Boot 3',
          'Data Structures & Algorithms (C++ / Java)',
          'Database Management Systems & MySQL Query Optimization',
          'RESTful APIs & Clean Architecture',
        ],
      },
      {
        degree: 'Intermediate (XII)',
        institution: 'Holy Angel Sr. Sec. School, Uttarakhand',
        duration: 'May 2023',
        grade: 'Percentage: 82%',
        highlights: ['Physics, Chemistry, Mathematics & Computer Science'],
      },
    ],
    quickFacts: [
      { label: 'Age', value: '22 Years' },
      { label: 'Degree', value: 'B.Tech CSE (Ongoing)' },
      { label: 'CGPA', value: '7.5 (NAAC A+)' },
      { label: 'SIH Hackathon', value: '1st Rank (50+ Teams)' },
      { label: 'Location', value: 'Dehradun, India' },
    ],
  },
  skills: [
    { id: 1, name: 'Java (17/21)', category: 'Backend', icon: 'Coffee', level: 95, experienceLevel: 'Expert' },
    { id: 2, name: 'Spring Boot 3', category: 'Backend', icon: 'Server', level: 94, experienceLevel: 'Expert' },
    { id: 3, name: 'Spring Security & JWT', category: 'Backend', icon: 'Shield', level: 90, experienceLevel: 'Advanced' },
    { id: 4, name: 'Hibernate ORM & Spring Data JPA', category: 'Backend', icon: 'HardDrive', level: 92, experienceLevel: 'Advanced' },
    { id: 5, name: 'RESTful APIs & Microservices', category: 'Backend', icon: 'Layers', level: 95, experienceLevel: 'Expert' },
    { id: 6, name: 'React.js', category: 'Frontend', icon: 'Globe', level: 90, experienceLevel: 'Expert' },
    { id: 7, name: 'JavaScript (ES6+)', category: 'Frontend', icon: 'FileCode', level: 88, experienceLevel: 'Advanced' },
    { id: 8, name: 'Tailwind CSS & HTML5/CSS3', category: 'Frontend', icon: 'Palette', level: 92, experienceLevel: 'Expert' },
    { id: 9, name: 'SQL (MySQL)', category: 'Database', icon: 'Database', level: 90, experienceLevel: 'Expert' },
    { id: 10, name: 'Redis', category: 'Database', icon: 'Database', level: 82, experienceLevel: 'Intermediate' },
    { id: 11, name: 'Git & GitHub', category: 'Tools', icon: 'GitBranch', level: 94, experienceLevel: 'Expert' },
    { id: 12, name: 'Docker', category: 'Tools', icon: 'Container', level: 84, experienceLevel: 'Intermediate' },
    { id: 13, name: 'Postman', category: 'Tools', icon: 'Send', level: 90, experienceLevel: 'Expert' },
    { id: 14, name: 'System Design & OOP', category: 'Tools', icon: 'Cpu', level: 88, experienceLevel: 'Advanced' },
    { id: 15, name: 'C++', category: 'Programming', icon: 'Code', level: 86, experienceLevel: 'Advanced' },
  ],
  projects: [
    {
      id: 1,
      title: 'College Management System (Full-Stack Web Application)',
      description: 'High-concurrency academic platform supporting Students, Faculty, and Admin using Java 21 Virtual Threads, Spring Security, and React.js.',
      longDescription: '• Architected a high-concurrency management platform supporting Students, Faculty, and Admin using Java 21 Virtual Threads for improved scalability and performance.\n• Engineered an Automated Faculty Status Engine that reduced scheduling conflicts by 50% through real-time timetable scanning and stateless session management using Spring Security.\n• Developed a dynamic exam seating visualization module using React.js and Tailwind CSS, transforming relational database records into an interactive graphical UI.\n• Improved application responsiveness by 40% through efficient client-side polling and centralized global exception handling for reliable real-time data synchronization.\n• Applied Clean Code principles and DTO patterns to decouple the persistence layer from the RESTful API layer, reducing payload size by 20%.',
      technologies: ['Java 21', 'Spring Boot 3', 'React.js', 'MySQL', 'Spring Security', 'Tailwind CSS'],
      githubUrl: 'https://github.com/hemant1883/Mini_CMS',
      liveDemoUrl: 'https://github.com/hemant1883/Mini_CMS',
      imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1200',
      screenshots: [],
      date: '2026',
      category: 'Full Stack',
      status: 'Completed',
      featured: true,
      result: '40% Higher Responsiveness & 50% Less Conflicts',
    },
    {
      id: 2,
      title: 'StayEase — Hotel Booking Web Application',
      description: 'Scalable hotel reservation platform featuring secure Role-Based Access Control (RBAC), JWT authentication, JPA entity relationships, and Railway deployment.',
      longDescription: '• Developed a scalable hotel reservation platform with secure Role-Based Access Control (RBAC), JWT-based authentication, and RESTful APIs for user and booking management.\n• Designed and implemented JPA entity relationships to manage hotel inventory efficiently while preventing race conditions during overlapping booking requests.\n• Optimized MySQL database performance by 30% through efficient indexing and custom SQL query optimization for complex availability searches.\n• Streamlined deployment using automated deployment workflows on Railway, ensuring 99.9% uptime for the production environment.',
      technologies: ['Java', 'Spring Boot', 'React.js', 'MySQL', 'JWT', 'Railway', 'Tailwind CSS'],
      githubUrl: 'https://github.com/hemant1883/HotelBooking',
      liveDemoUrl: 'https://github.com/hemant1883/HotelBooking',
      imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=1200',
      screenshots: [],
      date: '2026',
      category: 'Full Stack',
      status: 'Completed',
      featured: true,
      result: '30% DB Query Optimization & 99.9% Uptime',
    },
  ],
  certificates: [
    {
      id: 1,
      title: 'Certification – Full-Stack Java Development (Spring Boot & React)',
      organization: 'Full-Stack Java Program',
      issueDate: '2025',
      credentialId: 'FS-JAVA-2025',
      certificateUrl: 'https://github.com/hemant1883',
      description: 'Mastered Java 21, Spring Boot 3, Spring Security, Hibernate ORM, Spring Data JPA, and modern React.js frontend architecture.',
    },
  ],
  achievements: [
    {
      id: 1,
      title: 'Winner – Smart India Hackathon (SIH) 2025 Internal Ideathon',
      category: 'Hackathon Winner',
      organization: 'Smart India Hackathon (SIH) 2025 / SRHU',
      date: '2025',
      description: 'Ranked 1st among 50+ teams in the internal ideathon for architecting and presenting an automated high-impact software prototype.',
      proofUrl: 'https://github.com/hemant1883',
      icon: 'Trophy',
    },
    {
      id: 2,
      title: 'Top 50 Finalist – SAARTHI National Level Hackathon',
      category: 'National Hackathon',
      organization: 'SAARTHI National Level Hackathon',
      date: '2025',
      description: 'Selected among top 50 national finalist teams for engineering an innovative distributed full-stack architecture.',
      proofUrl: 'https://github.com/hemant1883/saarthi-hackthon1',
      icon: 'Award',
    },
    {
      id: 3,
      title: 'Certification – Full-Stack Java Development (Spring Boot & React)',
      category: 'Professional Certification',
      organization: 'Full-Stack Java Program',
      date: '2025',
      description: 'Mastered Java 21, Spring Boot 3, Spring Security, Hibernate ORM, Spring Data JPA, and modern React.js frontend architecture.',
      proofUrl: 'https://github.com/hemant1883',
      icon: 'Code',
    },
  ],
  messages: [],
  resume: {
    fileName: 'Hemant_Singh_Rana_Resume.pdf',
    fileUrl: 'https://drive.google.com/file/d/1Of5fiqg7i3X_nOlEFxTMLTTc0Os6xaux/view?pli=1',
    lastUpdated: '2026-08-17',
    fileSize: 'PDF',
  },
  githubStats: {
    username: 'hemant1883',
    publicRepos: 12,
    followers: 18,
    following: 15,
    totalStars: 15,
    languages: [
      { name: 'Java', percentage: 48, color: '#b07219' },
      { name: 'JavaScript', percentage: 28, color: '#f1e05a' },
      { name: 'TypeScript', percentage: 14, color: '#3178c6' },
      { name: 'HTML/CSS', percentage: 10, color: '#e34c26' },
    ],
    recentRepos: [
      {
        id: 1,
        name: 'Mini_CMS',
        description: 'College Management System in Spring Boot and React',
        url: 'https://github.com/hemant1883/Mini_CMS',
        language: 'Java',
        stars: 4,
        forks: 1,
        updatedAt: '2026-08-10',
      },
      {
        id: 2,
        name: 'HotelBooking',
        description: 'StayEase hotel reservation platform with JWT & MySQL',
        url: 'https://github.com/hemant1883/HotelBooking',
        language: 'Java',
        stars: 3,
        forks: 1,
        updatedAt: '2026-08-05',
      },
    ],
  },
  users: [
    {
      id: 1,
      username: 'admin',
      email: 'iamhemant1289@gmail.com',
      role: 'admin',
    },
  ],
};
